export const EDIT_ADDRESS = 'EDIT_ADDRESS';
export const ADD_ADDRESS_MODAL = 'ADD_ADDRESS_MODAL';
export const CHANGE_PASSWORD_MODAL = 'CHANGE_PASSWORD_MODAL';
export const EDIT_PROFILE_MODAL = 'EDIT_PROFILE_MODAL';
export const CONFIRMATION_MODAL = 'CONFIRMATION_MODAL';